version: '3.8'
services:
    surrealdb:
        container_name: surrealdb
        image: surrealdb/surrealdb:latest
        user: root
        ports:
            - "8000:8000"
        command: "start file:/data --auth --user root --pass root --client-ip socket"
        volumes:
            - surrealdb_data_container:/data
volumes:
    surrealdb_data_container:
